name: mlkit_base
description: "base application for different google MLkit models and functionalities"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #UI
  cupertino_icons: ^1.0.6

  #MLkit
  google_ml_kit: ^0.16.3
  google_mlkit_image_labeling: ^0.10.0


  #State management
  stacked: ^3.4.2
  stacked_services: ^1.5.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner:
  stacked_generator:


flutter:

  uses-material-design: true

  # To a  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
